### ISSUE TITLE
TC-32 Channel Number Mismatch

### ISSUE THREAD

**Issue by jeonghanlee** [epics-modules/measComp#20]
Hi @MarkRivers 

When the IOC starts, it prints out the following messages. 

```
022/09/12 09:58:08.316 asynPortDriver:setIntegerParam: port=TC32-1 error setting parameter 18 in list 32, invalid list
```
The error message will be gone if I use only `MAX_TEMPERATURE_IN` in both setIntegerParam calls as follows:

* `numTempChans_` is called from `AiETc32.cpp` https://github.com/epics-modules/measComp/blob/4d8e378884d1f802f18d712226ee301da0f3390c/measCompApp/src/drvMultiFunction.cpp#L1164
* `MAX_TEMPERATURE_IN` is defined in `drvMultiFunction.cpp` https://github.com/epics-modules/measComp/blob/4d8e378884d1f802f18d712226ee301da0f3390c/measCompApp/src/drvMultiFunction.cpp#L1093

The `uldaq` uses the hard-code number (64) in their Linux source `AiETc32.cpp`. I created an issue in ther repo https://github.com/mccdaq/uldaq/issues/48

In `drvMultiFunction.cpp`, we use this hard-code number (64) and our own defined number (32).

To reconcile this discrepancy between the two numbers, it may be better to add options to select the channel number within the measComp EPICS module to allow users to select a single TC-32 unit or a TC-32 unit with its additional expansion unit manually.

Or we use only `MAX_TEMPERATURE_IN` in our code, and use `MAX_TEMPERATURE_IN` instead of `numTempChans_`.

What do you think? 

@jeonghanlee

**Comment by MarkRivers** [comment]
I think we should just change MAX_TEMPERATURE_IN to 64.  That is used only for initializing the thermocouple type in the asynPortDriver parameter library.  Since there is a version of the TC32 with 64 channels this makes sense.  MAX_TEMPERATURE_IN is not used for controlling the number of temperature channels on a particular device.  This is done by inquiring their library to set numTempChans_.

Would this fix solve the problem?

**Comment by jeonghanlee** [comment]
Yes, changing to 64 solved my problem
